
package com.ezsoft.prmInterfaceHIS2008;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Service1Soap", targetNamespace = "http://tempuri.org/")
public interface Service1Soap {

	/**
	 * 
	 * @param endtime
	 * @param starttime
	 * @param rqtype
	 * @return returns
	 *         org.tempuri.QueryInpatientInfoResponse.QueryInpatientInfoResult
	 */
	@WebMethod(operationName = "QueryInpatientInfo", action = "http://tempuri.org/QueryInpatientInfo")
	@WebResult(name = "QueryInpatientInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryInpatientInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInpatientInfo")
	@ResponseWrapper(localName = "QueryInpatientInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInpatientInfoResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryInpatientInfoResponse.QueryInpatientInfoResult queryInpatientInfo(
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime,
			@WebParam(name = "rqtype", targetNamespace = "http://tempuri.org/") String rqtype);

	/**
	 * 
	 * @param endtime
	 * @param starttime
	 * @param type
	 * @param content
	 * @return returns
	 *         org.tempuri.QueryOperationInfoResponse.QueryOperationInfoResult
	 */
	@WebMethod(operationName = "QueryOperationInfo", action = "http://tempuri.org/QueryOperationInfo")
	@WebResult(name = "QueryOperationInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryOperationInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryOperationInfo")
	@ResponseWrapper(localName = "QueryOperationInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryOperationInfoResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryOperationInfoResponse.QueryOperationInfoResult queryOperationInfo(
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime,
			@WebParam(name = "type", targetNamespace = "http://tempuri.org/") String type,
			@WebParam(name = "content", targetNamespace = "http://tempuri.org/") String content);

	/**
	 * 
	 * @param zyh
	 * @return returns
	 *         org.tempuri.QueryOperationInfoByZyhResponse.QueryOperationInfoByZyhResult
	 */
	@WebMethod(operationName = "QueryOperationInfoByZyh", action = "http://tempuri.org/QueryOperationInfoByZyh")
	@WebResult(name = "QueryOperationInfoByZyhResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryOperationInfoByZyh", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryOperationInfoByZyh")
	@ResponseWrapper(localName = "QueryOperationInfoByZyhResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryOperationInfoByZyhResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryOperationInfoByZyhResponse.QueryOperationInfoByZyhResult queryOperationInfoByZyh(
			@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh);

	/**
	 * 
	 * @param zyhm
	 * @return returns
	 *         org.tempuri.QueryInpatientDAResponse.QueryInpatientDAResult
	 */
	@WebMethod(operationName = "QueryInpatientDA", action = "http://tempuri.org/QueryInpatientDA")
	@WebResult(name = "QueryInpatientDAResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryInpatientDA", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInpatientDA")
	@ResponseWrapper(localName = "QueryInpatientDAResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInpatientDAResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryInpatientDAResponse.QueryInpatientDAResult queryInpatientDA(
			@WebParam(name = "zyhm", targetNamespace = "http://tempuri.org/") String zyhm);

	/**
	 * 
	 * @return returns org.tempuri.QueryBrxzResponse.QueryBrxzResult
	 */
	@WebMethod(operationName = "QueryBrxz", action = "http://tempuri.org/QueryBrxz")
	@WebResult(name = "QueryBrxzResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryBrxz", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryBrxz")
	@ResponseWrapper(localName = "QueryBrxzResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryBrxzResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryBrxzResponse.QueryBrxzResult queryBrxz();

	/**
	 * 
	 * @return returns org.tempuri.QuerysfResponse.QuerysfResult
	 */
	@WebMethod(operationName = "Querysf", action = "http://tempuri.org/Querysf")
	@WebResult(name = "QuerysfResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Querysf", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Querysf")
	@ResponseWrapper(localName = "QuerysfResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QuerysfResponse")
	public com.ezsoft.prmInterfaceHIS2008.QuerysfResponse.QuerysfResult querysf();

	/**
	 * 
	 * @return returns org.tempuri.QueryJgResponse.QueryJgResult
	 */
	@WebMethod(operationName = "QueryJg", action = "http://tempuri.org/QueryJg")
	@WebResult(name = "QueryJgResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryJg", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryJg")
	@ResponseWrapper(localName = "QueryJgResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryJgResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryJgResponse.QueryJgResult queryJg();

	/**
	 * 
	 * @return returns org.tempuri.QueryMzResponse.QueryMzResult
	 */
	@WebMethod(operationName = "QueryMz", action = "http://tempuri.org/QueryMz")
	@WebResult(name = "QueryMzResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryMz", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMz")
	@ResponseWrapper(localName = "QueryMzResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMzResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryMzResponse.QueryMzResult queryMz();

	/**
	 * 
	 * @return returns org.tempuri.QueryGxResponse.QueryGxResult
	 */
	@WebMethod(operationName = "QueryGx", action = "http://tempuri.org/QueryGx")
	@WebResult(name = "QueryGxResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryGx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryGx")
	@ResponseWrapper(localName = "QueryGxResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryGxResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryGxResponse.QueryGxResult queryGx();

	/**
	 * 
	 * @return returns org.tempuri.QueryZyResponse.QueryZyResult
	 */
	@WebMethod(operationName = "QueryZy", action = "http://tempuri.org/QueryZy")
	@WebResult(name = "QueryZyResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryZy", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryZy")
	@ResponseWrapper(localName = "QueryZyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryZyResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryZyResponse.QueryZyResult queryZy();

	/**
	 * 
	 * @param zyh
	 * @return returns org.tempuri.QueryBrblResponse.QueryBrblResult
	 */
	@WebMethod(operationName = "QueryBrbl", action = "http://tempuri.org/QueryBrbl")
	@WebResult(name = "QueryBrblResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryBrbl", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryBrbl")
	@ResponseWrapper(localName = "QueryBrblResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryBrblResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryBrblResponse.QueryBrblResult queryBrbl(
			@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh);

	/**
	 * 
	 * @return returns org.tempuri.QueryMzKsResponse.QueryMzKsResult
	 */
	@WebMethod(operationName = "QueryMzKs", action = "http://tempuri.org/QueryMzKs")
	@WebResult(name = "QueryMzKsResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryMzKs", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMzKs")
	@ResponseWrapper(localName = "QueryMzKsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMzKsResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryMzKsResponse.QueryMzKsResult queryMzKs();

	/**
	 * 
	 * @param ksdm
	 * @param qsrq
	 * @return returns org.tempuri.QueryKsMzPbResponse.QueryKsMzPbResult
	 */
	@WebMethod(operationName = "QueryKsMzPb", action = "http://tempuri.org/QueryKsMzPb")
	@WebResult(name = "QueryKsMzPbResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryKsMzPb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryKsMzPb")
	@ResponseWrapper(localName = "QueryKsMzPbResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryKsMzPbResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryKsMzPbResponse.QueryKsMzPbResult queryKsMzPb(
			@WebParam(name = "ksdm", targetNamespace = "http://tempuri.org/") String ksdm,
			@WebParam(name = "qsrq", targetNamespace = "http://tempuri.org/") String qsrq);

	/**
	 * 
	 * @param ksdm
	 * @return returns org.tempuri.QueryKsBedInfoResponse.QueryKsBedInfoResult
	 */
	@WebMethod(operationName = "QueryKsBedInfo", action = "http://tempuri.org/QueryKsBedInfo")
	@WebResult(name = "QueryKsBedInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryKsBedInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryKsBedInfo")
	@ResponseWrapper(localName = "QueryKsBedInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryKsBedInfoResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryKsBedInfoResponse.QueryKsBedInfoResult queryKsBedInfo(
			@WebParam(name = "ksdm", targetNamespace = "http://tempuri.org/") String ksdm);

	/**
	 * 
	 * @return returns org.tempuri.QueryBqKsResponse.QueryBqKsResult
	 */
	@WebMethod(operationName = "QueryBqKs", action = "http://tempuri.org/QueryBqKs")
	@WebResult(name = "QueryBqKsResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryBqKs", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryBqKs")
	@ResponseWrapper(localName = "QueryBqKsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryBqKsResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryBqKsResponse.QueryBqKsResult queryBqKs();

	/**
	 * 
	 * @param type
	 * @param content
	 * @return returns org.tempuri.QueryZyjlResponse.QueryZyjlResult
	 */
	@WebMethod(operationName = "QueryZyjl", action = "http://tempuri.org/QueryZyjl")
	@WebResult(name = "QueryZyjlResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryZyjl", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryZyjl")
	@ResponseWrapper(localName = "QueryZyjlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryZyjlResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryZyjlResponse.QueryZyjlResult queryZyjl(
			@WebParam(name = "type", targetNamespace = "http://tempuri.org/") String type,
			@WebParam(name = "content", targetNamespace = "http://tempuri.org/") String content);

	/**
	 * 
	 * @param cypb
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryCypb", action = "http://tempuri.org/QueryCypb")
	@WebResult(name = "QueryCypbResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryCypb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryCypb")
	@ResponseWrapper(localName = "QueryCypbResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryCypbResponse")
	public String queryCypb(@WebParam(name = "cypb", targetNamespace = "http://tempuri.org/") int cypb);

	/**
	 * 
	 * @param cypb
	 * @param zyh
	 * @return returns org.tempuri.QueryGrzkResponse.QueryGrzkResult
	 */
	@WebMethod(operationName = "QueryGrzk", action = "http://tempuri.org/QueryGrzk")
	@WebResult(name = "QueryGrzkResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryGrzk", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryGrzk")
	@ResponseWrapper(localName = "QueryGrzkResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryGrzkResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryGrzkResponse.QueryGrzkResult queryGrzk(
			@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh,
			@WebParam(name = "cypb", targetNamespace = "http://tempuri.org/") int cypb);

	/**
	 * 
	 * @return returns org.tempuri.QueryFymcResponse.QueryFymcResult
	 */
	@WebMethod(operationName = "QueryFymc", action = "http://tempuri.org/QueryFymc")
	@WebResult(name = "QueryFymcResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryFymc", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryFymc")
	@ResponseWrapper(localName = "QueryFymcResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryFymcResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryFymcResponse.QueryFymcResult queryFymc();

	/**
	 * 
	 * @param zygb
	 * @param cypb
	 * @param zyh
	 * @return returns org.tempuri.QueryXMMXResponse.QueryXMMXResult
	 */
	@WebMethod(operationName = "QueryXMMX", action = "http://tempuri.org/QueryXMMX")
	@WebResult(name = "QueryXMMXResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryXMMX", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryXMMX")
	@ResponseWrapper(localName = "QueryXMMXResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryXMMXResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryXMMXResponse.QueryXMMXResult queryXMMX(
			@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh,
			@WebParam(name = "zygb", targetNamespace = "http://tempuri.org/") int zygb,
			@WebParam(name = "cypb", targetNamespace = "http://tempuri.org/") int cypb);

	/**
	 * 
	 * @param fyrq
	 * @param zygb
	 * @param cypb
	 * @param zyh
	 * @return returns org.tempuri.QueryFYMXResponse.QueryFYMXResult
	 */
	@WebMethod(operationName = "QueryFYMX", action = "http://tempuri.org/QueryFYMX")
	@WebResult(name = "QueryFYMXResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryFYMX", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryFYMX")
	@ResponseWrapper(localName = "QueryFYMXResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryFYMXResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryFYMXResponse.QueryFYMXResult queryFYMX(
			@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh,
			@WebParam(name = "zygb", targetNamespace = "http://tempuri.org/") int zygb,
			@WebParam(name = "fyrq", targetNamespace = "http://tempuri.org/") String fyrq,
			@WebParam(name = "cypb", targetNamespace = "http://tempuri.org/") int cypb);

	/**
	 * 
	 * @param rq
	 * @return returns org.tempuri.QueryCyBirthResponse.QueryCyBirthResult
	 */
	@WebMethod(operationName = "QueryCyBirth", action = "http://tempuri.org/QueryCyBirth")
	@WebResult(name = "QueryCyBirthResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryCyBirth", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryCyBirth")
	@ResponseWrapper(localName = "QueryCyBirthResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryCyBirthResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryCyBirthResponse.QueryCyBirthResult queryCyBirth(
			@WebParam(name = "rq", targetNamespace = "http://tempuri.org/") String rq);

	/**
	 * 
	 * @param rq
	 * @return returns org.tempuri.QueryZyBirthResponse.QueryZyBirthResult
	 */
	@WebMethod(operationName = "QueryZyBirth", action = "http://tempuri.org/QueryZyBirth")
	@WebResult(name = "QueryZyBirthResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryZyBirth", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryZyBirth")
	@ResponseWrapper(localName = "QueryZyBirthResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryZyBirthResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryZyBirthResponse.QueryZyBirthResult queryZyBirth(
			@WebParam(name = "rq", targetNamespace = "http://tempuri.org/") String rq);

	/**
	 * 
	 * @param rq
	 * @return returns org.tempuri.QueryHfrwResponse.QueryHfrwResult
	 */
	@WebMethod(operationName = "QueryHfrw", action = "http://tempuri.org/QueryHfrw")
	@WebResult(name = "QueryHfrwResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryHfrw", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryHfrw")
	@ResponseWrapper(localName = "QueryHfrwResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryHfrwResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryHfrwResponse.QueryHfrwResult queryHfrw(
			@WebParam(name = "rq", targetNamespace = "http://tempuri.org/") String rq);

	/**
	 * 
	 * @param zyhm
	 * @return returns org.tempuri.QueryHfrwByZyhmResponse.QueryHfrwByZyhmResult
	 */
	@WebMethod(operationName = "QueryHfrwByZyhm", action = "http://tempuri.org/QueryHfrwByZyhm")
	@WebResult(name = "QueryHfrwByZyhmResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryHfrwByZyhm", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryHfrwByZyhm")
	@ResponseWrapper(localName = "QueryHfrwByZyhmResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryHfrwByZyhmResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryHfrwByZyhmResponse.QueryHfrwByZyhmResult queryHfrwByZyhm(
			@WebParam(name = "zyhm", targetNamespace = "http://tempuri.org/") String zyhm);

	/**
	 * 
	 * @param jlxh
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DeleteHfrwByJlxh", action = "http://tempuri.org/DeleteHfrwByJlxh")
	@WebResult(name = "DeleteHfrwByJlxhResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "DeleteHfrwByJlxh", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteHfrwByJlxh")
	@ResponseWrapper(localName = "DeleteHfrwByJlxhResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteHfrwByJlxhResponse")
	public String deleteHfrwByJlxh(@WebParam(name = "jlxh", targetNamespace = "http://tempuri.org/") String jlxh);

	/**
	 * 
	 * @param zyh
	 * @return returns
	 *         org.tempuri.QueryInpatientInfoByZyhResponse.QueryInpatientInfoByZyhResult
	 */
	@WebMethod(operationName = "QueryInpatientInfoByZyh", action = "http://tempuri.org/QueryInpatientInfoByZyh")
	@WebResult(name = "QueryInpatientInfoByZyhResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryInpatientInfoByZyh", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInpatientInfoByZyh")
	@ResponseWrapper(localName = "QueryInpatientInfoByZyhResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInpatientInfoByZyhResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryInpatientInfoByZyhResponse.QueryInpatientInfoByZyhResult queryInpatientInfoByZyh(
			@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh);

	/**
	 * 
	 * @param zyhmc
	 * @return returns
	 *         org.tempuri.QueryInpatientInfoByZyhmcResponse.QueryInpatientInfoByZyhmcResult
	 */
	@WebMethod(operationName = "QueryInpatientInfoByZyhmc", action = "http://tempuri.org/QueryInpatientInfoByZyhmc")
	@WebResult(name = "QueryInpatientInfoByZyhmcResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryInpatientInfoByZyhmc", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInpatientInfoByZyhmc")
	@ResponseWrapper(localName = "QueryInpatientInfoByZyhmcResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInpatientInfoByZyhmcResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryInpatientInfoByZyhmcResponse.QueryInpatientInfoByZyhmcResult queryInpatientInfoByZyhmc(
			@WebParam(name = "zyhmc", targetNamespace = "http://tempuri.org/") String zyhmc);

	/**
	 * 
	 * @param ygdm
	 * @return returns org.tempuri.QueryDocInfoResponse.QueryDocInfoResult
	 */
	@WebMethod(operationName = "QueryDocInfo", action = "http://tempuri.org/QueryDocInfo")
	@WebResult(name = "QueryDocInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryDocInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryDocInfo")
	@ResponseWrapper(localName = "QueryDocInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryDocInfoResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryDocInfoResponse.QueryDocInfoResult queryDocInfo(
			@WebParam(name = "ygdm", targetNamespace = "http://tempuri.org/") String ygdm);

	/**
	 * 
	 * @param zyh
	 * @param bz
	 * @param phonenum
	 * @param zyhm
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UpdatePhone", action = "http://tempuri.org/UpdatePhone")
	@WebResult(name = "UpdatePhoneResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "UpdatePhone", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdatePhone")
	@ResponseWrapper(localName = "UpdatePhoneResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdatePhoneResponse")
	public String updatePhone(@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh,
			@WebParam(name = "zyhm", targetNamespace = "http://tempuri.org/") String zyhm,
			@WebParam(name = "phonenum", targetNamespace = "http://tempuri.org/") String phonenum,
			@WebParam(name = "bz", targetNamespace = "http://tempuri.org/") String bz);

	/**
	 * 
	 * @param phone
	 * @param content
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SentMessageToPat", action = "http://tempuri.org/SentMessageToPat")
	@WebResult(name = "SentMessageToPatResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SentMessageToPat", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SentMessageToPat")
	@ResponseWrapper(localName = "SentMessageToPatResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SentMessageToPatResponse")
	public String sentMessageToPat(@WebParam(name = "phone", targetNamespace = "http://tempuri.org/") String phone,
			@WebParam(name = "content", targetNamespace = "http://tempuri.org/") String content);

	/**
	 * 
	 * @param phone
	 * @param content
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SentMsg", action = "http://tempuri.org/SentMsg")
	@WebResult(name = "SentMsgResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SentMsg", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SentMsg")
	@ResponseWrapper(localName = "SentMsgResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SentMsgResponse")
	public String sentMsg(@WebParam(name = "phone", targetNamespace = "http://tempuri.org/") String phone,
			@WebParam(name = "content", targetNamespace = "http://tempuri.org/") String content);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetMsg", action = "http://tempuri.org/GetMsg")
	@WebResult(name = "GetMsgResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetMsg", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMsg")
	@ResponseWrapper(localName = "GetMsgResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMsgResponse")
	public String getMsg();

	/**
	 * 
	 * @return returns org.tempuri.QueryAllKSResponse.QueryAllKSResult
	 */
	@WebMethod(operationName = "QueryAllKS", action = "http://tempuri.org/QueryAllKS")
	@WebResult(name = "QueryAllKSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryAllKS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryAllKS")
	@ResponseWrapper(localName = "QueryAllKSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryAllKSResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryAllKSResponse.QueryAllKSResult queryAllKS();

	/**
	 * 
	 * @param zyh
	 * @return returns
	 *         org.tempuri.QueryHFInpatientInfoByZyhResponse.QueryHFInpatientInfoByZyhResult
	 */
	@WebMethod(operationName = "QueryHFInpatientInfoByZyh", action = "http://tempuri.org/QueryHFInpatientInfoByZyh")
	@WebResult(name = "QueryHFInpatientInfoByZyhResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryHFInpatientInfoByZyh", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryHFInpatientInfoByZyh")
	@ResponseWrapper(localName = "QueryHFInpatientInfoByZyhResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryHFInpatientInfoByZyhResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryHFInpatientInfoByZyhResponse.QueryHFInpatientInfoByZyhResult queryHFInpatientInfoByZyh(
			@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh);

	/**
	 * 
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.QueryMZFZSResponse.QueryMZFZSResult
	 */
	@WebMethod(operationName = "QueryMZFZS", action = "http://tempuri.org/QueryMZFZS")
	@WebResult(name = "QueryMZFZSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryMZFZS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMZFZS")
	@ResponseWrapper(localName = "QueryMZFZSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMZFZSResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryMZFZSResponse.QueryMZFZSResult queryMZFZS(
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime);

	/**
	 * 
	 * @param zyh
	 * @return returns org.tempuri.QueryCYFileNameResponse.QueryCYFileNameResult
	 */
	@WebMethod(operationName = "QueryCYFileName", action = "http://tempuri.org/QueryCYFileName")
	@WebResult(name = "QueryCYFileNameResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryCYFileName", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryCYFileName")
	@ResponseWrapper(localName = "QueryCYFileNameResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryCYFileNameResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryCYFileNameResponse.QueryCYFileNameResult queryCYFileName(
			@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh);

	/**
	 * 
	 * @param zyh
	 * @return returns org.tempuri.QueryRYFileNameResponse.QueryRYFileNameResult
	 */
	@WebMethod(operationName = "QueryRYFileName", action = "http://tempuri.org/QueryRYFileName")
	@WebResult(name = "QueryRYFileNameResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryRYFileName", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryRYFileName")
	@ResponseWrapper(localName = "QueryRYFileNameResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryRYFileNameResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryRYFileNameResponse.QueryRYFileNameResult queryRYFileName(
			@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh);

	/**
	 * 
	 * @param xz
	 * @param endDate
	 * @param startDate
	 * @return returns
	 *         org.tempuri.QueryCyFileStringResponse.QueryCyFileStringResult
	 */
	@WebMethod(operationName = "QueryCyFileString", action = "http://tempuri.org/QueryCyFileString")
	@WebResult(name = "QueryCyFileStringResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryCyFileString", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryCyFileString")
	@ResponseWrapper(localName = "QueryCyFileStringResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryCyFileStringResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryCyFileStringResponse.QueryCyFileStringResult queryCyFileString(
			@WebParam(name = "xz", targetNamespace = "http://tempuri.org/") String xz,
			@WebParam(name = "startDate", targetNamespace = "http://tempuri.org/") String startDate,
			@WebParam(name = "endDate", targetNamespace = "http://tempuri.org/") String endDate);

	/**
	 * 
	 * @param endtime
	 * @param starttime
	 * @return returns
	 *         org.tempuri.QueryPhoneManageByRyrqResponse.QueryPhoneManageByRyrqResult
	 */
	@WebMethod(operationName = "QueryPhoneManageByRyrq", action = "http://tempuri.org/QueryPhoneManageByRyrq")
	@WebResult(name = "QueryPhoneManageByRyrqResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryPhoneManageByRyrq", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryPhoneManageByRyrq")
	@ResponseWrapper(localName = "QueryPhoneManageByRyrqResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryPhoneManageByRyrqResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryPhoneManageByRyrqResponse.QueryPhoneManageByRyrqResult queryPhoneManageByRyrq(
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param ysgh
	 * @param rq
	 * @return returns
	 *         org.tempuri.QueryMzSpecialPationInfoByRqMzhmYsghResponse.QueryMzSpecialPationInfoByRqMzhmYsghResult
	 */
	@WebMethod(operationName = "QueryMzSpecialPationInfoByRqMzhmYsgh", action = "http://tempuri.org/QueryMzSpecialPationInfoByRqMzhmYsgh")
	@WebResult(name = "QueryMzSpecialPationInfoByRqMzhmYsghResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryMzSpecialPationInfoByRqMzhmYsgh", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMzSpecialPationInfoByRqMzhmYsgh")
	@ResponseWrapper(localName = "QueryMzSpecialPationInfoByRqMzhmYsghResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMzSpecialPationInfoByRqMzhmYsghResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryMzSpecialPationInfoByRqMzhmYsghResponse.QueryMzSpecialPationInfoByRqMzhmYsghResult queryMzSpecialPationInfoByRqMzhmYsgh(
			@WebParam(name = "mzhm", targetNamespace = "http://tempuri.org/") String mzhm,
			@WebParam(name = "ysgh", targetNamespace = "http://tempuri.org/") String ysgh,
			@WebParam(name = "rq", targetNamespace = "http://tempuri.org/") String rq);

	/**
	 * 
	 * @param zyh
	 * @return returns
	 *         org.tempuri.QueryZySpecialPationInfoByZyhResponse.QueryZySpecialPationInfoByZyhResult
	 */
	@WebMethod(operationName = "QueryZySpecialPationInfoByZyh", action = "http://tempuri.org/QueryZySpecialPationInfoByZyh")
	@WebResult(name = "QueryZySpecialPationInfoByZyhResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryZySpecialPationInfoByZyh", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryZySpecialPationInfoByZyh")
	@ResponseWrapper(localName = "QueryZySpecialPationInfoByZyhResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryZySpecialPationInfoByZyhResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryZySpecialPationInfoByZyhResponse.QueryZySpecialPationInfoByZyhResult queryZySpecialPationInfoByZyh(
			@WebParam(name = "zyh", targetNamespace = "http://tempuri.org/") String zyh);

	/**
	 * 
	 * @param mzzyh
	 * @param endtime
	 * @param starttime
	 * @return returns
	 *         org.tempuri.QueryElectrocarDiogramByMZZYHAndTimeResponse.QueryElectrocarDiogramByMZZYHAndTimeResult
	 */
	@WebMethod(operationName = "QueryElectrocarDiogramByMZZYHAndTime", action = "http://tempuri.org/QueryElectrocarDiogramByMZZYHAndTime")
	@WebResult(name = "QueryElectrocarDiogramByMZZYHAndTimeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryElectrocarDiogramByMZZYHAndTime", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryElectrocarDiogramByMZZYHAndTime")
	@ResponseWrapper(localName = "QueryElectrocarDiogramByMZZYHAndTimeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryElectrocarDiogramByMZZYHAndTimeResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryElectrocarDiogramByMZZYHAndTimeResponse.QueryElectrocarDiogramByMZZYHAndTimeResult queryElectrocarDiogramByMZZYHAndTime(
			@WebParam(name = "mzzyh", targetNamespace = "http://tempuri.org/") String mzzyh,
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @return returns org.tempuri.QueryMZbrdaResponse.QueryMZbrdaResult
	 */
	@WebMethod(operationName = "QueryMZbrda", action = "http://tempuri.org/QueryMZbrda")
	@WebResult(name = "QueryMZbrdaResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryMZbrda", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMZbrda")
	@ResponseWrapper(localName = "QueryMZbrdaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMZbrdaResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryMZbrdaResponse.QueryMZbrdaResult queryMZbrda(
			@WebParam(name = "mzhm", targetNamespace = "http://tempuri.org/") String mzhm);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.QueryMZBrYJJCResponse.QueryMZBrYJJCResult
	 */
	@WebMethod(operationName = "QueryMZBrYJJC", action = "http://tempuri.org/QueryMZBrYJJC")
	@WebResult(name = "QueryMZBrYJJCResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryMZBrYJJC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMZBrYJJC")
	@ResponseWrapper(localName = "QueryMZBrYJJCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMZBrYJJCResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryMZBrYJJCResponse.QueryMZBrYJJCResult queryMZBrYJJC(
			@WebParam(name = "mzhm", targetNamespace = "http://tempuri.org/") String mzhm,
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime);

	/**
	 * 
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.QueryYYGHByTimeResponse.QueryYYGHByTimeResult
	 */
	@WebMethod(operationName = "QueryYYGHByTime", action = "http://tempuri.org/QueryYYGHByTime")
	@WebResult(name = "QueryYYGHByTimeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryYYGHByTime", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryYYGHByTime")
	@ResponseWrapper(localName = "QueryYYGHByTimeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryYYGHByTimeResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryYYGHByTimeResponse.QueryYYGHByTimeResult queryYYGHByTime(
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.QueryYYGHByMZHMResponse.QueryYYGHByMZHMResult
	 */
	@WebMethod(operationName = "QueryYYGHByMZHM", action = "http://tempuri.org/QueryYYGHByMZHM")
	@WebResult(name = "QueryYYGHByMZHMResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryYYGHByMZHM", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryYYGHByMZHM")
	@ResponseWrapper(localName = "QueryYYGHByMZHMResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryYYGHByMZHMResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryYYGHByMZHMResponse.QueryYYGHByMZHMResult queryYYGHByMZHM(
			@WebParam(name = "mzhm", targetNamespace = "http://tempuri.org/") String mzhm,
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param pb
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UpdateJLBBZ", action = "http://tempuri.org/UpdateJLBBZ")
	@WebResult(name = "UpdateJLBBZResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "UpdateJLBBZ", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateJLBBZ")
	@ResponseWrapper(localName = "UpdateJLBBZResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateJLBBZResponse")
	public String updateJLBBZ(@WebParam(name = "mzhm", targetNamespace = "http://tempuri.org/") String mzhm,
			@WebParam(name = "pb", targetNamespace = "http://tempuri.org/") int pb);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns
	 *         org.tempuri.QueryLabItemNoByMzhmAndTimeResponse.QueryLabItemNoByMzhmAndTimeResult
	 */
	@WebMethod(operationName = "QueryLabItemNoByMzhmAndTime", action = "http://tempuri.org/QueryLabItemNoByMzhmAndTime")
	@WebResult(name = "QueryLabItemNoByMzhmAndTimeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryLabItemNoByMzhmAndTime", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryLabItemNoByMzhmAndTime")
	@ResponseWrapper(localName = "QueryLabItemNoByMzhmAndTimeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryLabItemNoByMzhmAndTimeResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryLabItemNoByMzhmAndTimeResponse.QueryLabItemNoByMzhmAndTimeResult queryLabItemNoByMzhmAndTime(
			@WebParam(name = "mzhm", targetNamespace = "http://tempuri.org/") String mzhm,
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param labItemName
	 * @param endtime
	 * @param starttime
	 * @return returns
	 *         org.tempuri.QueryLisResultByMzhmAndTimeAndLabItemNameResponse.QueryLisResultByMzhmAndTimeAndLabItemNameResult
	 */
	@WebMethod(operationName = "QueryLisResultByMzhmAndTimeAndLabItemName", action = "http://tempuri.org/QueryLisResultByMzhmAndTimeAndLabItemName")
	@WebResult(name = "QueryLisResultByMzhmAndTimeAndLabItemNameResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryLisResultByMzhmAndTimeAndLabItemName", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryLisResultByMzhmAndTimeAndLabItemName")
	@ResponseWrapper(localName = "QueryLisResultByMzhmAndTimeAndLabItemNameResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryLisResultByMzhmAndTimeAndLabItemNameResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryLisResultByMzhmAndTimeAndLabItemNameResponse.QueryLisResultByMzhmAndTimeAndLabItemNameResult queryLisResultByMzhmAndTimeAndLabItemName(
			@WebParam(name = "mzhm", targetNamespace = "http://tempuri.org/") String mzhm,
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime,
			@WebParam(name = "LabItemName", targetNamespace = "http://tempuri.org/") String labItemName);

	/**
	 * 
	 * @param labItemNo
	 * @return returns
	 *         org.tempuri.QueryLisResultByLabItemNoResponse.QueryLisResultByLabItemNoResult
	 */
	@WebMethod(operationName = "QueryLisResultByLabItemNo", action = "http://tempuri.org/QueryLisResultByLabItemNo")
	@WebResult(name = "QueryLisResultByLabItemNoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryLisResultByLabItemNo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryLisResultByLabItemNo")
	@ResponseWrapper(localName = "QueryLisResultByLabItemNoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryLisResultByLabItemNoResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryLisResultByLabItemNoResponse.QueryLisResultByLabItemNoResult queryLisResultByLabItemNo(
			@WebParam(name = "LabItemNo", targetNamespace = "http://tempuri.org/") String labItemNo);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns
	 *         org.tempuri.QueryJZJLByMzhmAndTimeResponse.QueryJZJLByMzhmAndTimeResult
	 */
	@WebMethod(operationName = "QueryJZJLByMzhmAndTime", action = "http://tempuri.org/QueryJZJLByMzhmAndTime")
	@WebResult(name = "QueryJZJLByMzhmAndTimeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryJZJLByMzhmAndTime", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryJZJLByMzhmAndTime")
	@ResponseWrapper(localName = "QueryJZJLByMzhmAndTimeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryJZJLByMzhmAndTimeResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryJZJLByMzhmAndTimeResponse.QueryJZJLByMzhmAndTimeResult queryJZJLByMzhmAndTime(
			@WebParam(name = "mzhm", targetNamespace = "http://tempuri.org/") String mzhm,
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns
	 *         org.tempuri.QueryBUltrasoundByMzhmAndTimeResponse.QueryBUltrasoundByMzhmAndTimeResult
	 */
	@WebMethod(operationName = "QueryBUltrasoundByMzhmAndTime", action = "http://tempuri.org/QueryBUltrasoundByMzhmAndTime")
	@WebResult(name = "QueryBUltrasoundByMzhmAndTimeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryBUltrasoundByMzhmAndTime", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryBUltrasoundByMzhmAndTime")
	@ResponseWrapper(localName = "QueryBUltrasoundByMzhmAndTimeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryBUltrasoundByMzhmAndTimeResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryBUltrasoundByMzhmAndTimeResponse.QueryBUltrasoundByMzhmAndTimeResult queryBUltrasoundByMzhmAndTime(
			@WebParam(name = "mzhm", targetNamespace = "http://tempuri.org/") String mzhm,
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns
	 *         org.tempuri.QueryElectrocarDiogramByMzhmAndTimeResponse.QueryElectrocarDiogramByMzhmAndTimeResult
	 */
	@WebMethod(operationName = "QueryElectrocarDiogramByMzhmAndTime", action = "http://tempuri.org/QueryElectrocarDiogramByMzhmAndTime")
	@WebResult(name = "QueryElectrocarDiogramByMzhmAndTimeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryElectrocarDiogramByMzhmAndTime", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryElectrocarDiogramByMzhmAndTime")
	@ResponseWrapper(localName = "QueryElectrocarDiogramByMzhmAndTimeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryElectrocarDiogramByMzhmAndTimeResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryElectrocarDiogramByMzhmAndTimeResponse.QueryElectrocarDiogramByMzhmAndTimeResult queryElectrocarDiogramByMzhmAndTime(
			@WebParam(name = "mzhm", targetNamespace = "http://tempuri.org/") String mzhm,
			@WebParam(name = "starttime", targetNamespace = "http://tempuri.org/") String starttime,
			@WebParam(name = "endtime", targetNamespace = "http://tempuri.org/") String endtime);

	/**
	 * 
	 * @param rq
	 * @return returns org.tempuri.QueryJLBBirthResponse.QueryJLBBirthResult
	 */
	@WebMethod(operationName = "QueryJLBBirth", action = "http://tempuri.org/QueryJLBBirth")
	@WebResult(name = "QueryJLBBirthResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryJLBBirth", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryJLBBirth")
	@ResponseWrapper(localName = "QueryJLBBirthResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryJLBBirthResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryJLBBirthResponse.QueryJLBBirthResult queryJLBBirth(
			@WebParam(name = "rq", targetNamespace = "http://tempuri.org/") String rq);

	/**
	 * 
	 * @param smID
	 * @param rq
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryMOMSG", action = "http://tempuri.org/QueryMOMSG")
	@WebResult(name = "QueryMOMSGResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryMOMSG", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMOMSG")
	@ResponseWrapper(localName = "QueryMOMSGResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMOMSGResponse")
	public String queryMOMSG(@WebParam(name = "SM_ID", targetNamespace = "http://tempuri.org/") long smID,
			@WebParam(name = "rq", targetNamespace = "http://tempuri.org/") String rq);

	/**
	 * 
	 * @param phone
	 * @param srcId
	 * @param id
	 * @param content
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SentMessageToPatByID", action = "http://tempuri.org/SentMessageToPatByID")
	@WebResult(name = "SentMessageToPatByIDResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SentMessageToPatByID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SentMessageToPatByID")
	@ResponseWrapper(localName = "SentMessageToPatByIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SentMessageToPatByIDResponse")
	public String sentMessageToPatByID(@WebParam(name = "id", targetNamespace = "http://tempuri.org/") long id,
			@WebParam(name = "src_id", targetNamespace = "http://tempuri.org/") long srcId,
			@WebParam(name = "phone", targetNamespace = "http://tempuri.org/") String phone,
			@WebParam(name = "content", targetNamespace = "http://tempuri.org/") String content);

	/**
	 * 
	 * @param sfbz
	 * @return returns
	 *         org.tempuri.QueryMzAtscBySfbzResponse.QueryMzAtscBySfbzResult
	 */
	@WebMethod(operationName = "QueryMzAtscBySfbz", action = "http://tempuri.org/QueryMzAtscBySfbz")
	@WebResult(name = "QueryMzAtscBySfbzResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryMzAtscBySfbz", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMzAtscBySfbz")
	@ResponseWrapper(localName = "QueryMzAtscBySfbzResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryMzAtscBySfbzResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryMzAtscBySfbzResponse.QueryMzAtscBySfbzResult queryMzAtscBySfbz(
			@WebParam(name = "sfbz", targetNamespace = "http://tempuri.org/") String sfbz);

	/**
	 * 
	 * @param jlxh
	 * @param sfbz
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UpdateMzAtscSfbz", action = "http://tempuri.org/UpdateMzAtscSfbz")
	@WebResult(name = "UpdateMzAtscSfbzResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "UpdateMzAtscSfbz", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateMzAtscSfbz")
	@ResponseWrapper(localName = "UpdateMzAtscSfbzResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateMzAtscSfbzResponse")
	public String updateMzAtscSfbz(@WebParam(name = "jlxh", targetNamespace = "http://tempuri.org/") long jlxh,
			@WebParam(name = "sfbz", targetNamespace = "http://tempuri.org/") int sfbz);

	/**
	 * 
	 * @param sfbz
	 * @return returns
	 *         org.tempuri.QueryByMzscBySfbzResponse.QueryByMzscBySfbzResult
	 */
	@WebMethod(operationName = "QueryByMzscBySfbz", action = "http://tempuri.org/QueryByMzscBySfbz")
	@WebResult(name = "QueryByMzscBySfbzResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "QueryByMzscBySfbz", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryByMzscBySfbz")
	@ResponseWrapper(localName = "QueryByMzscBySfbzResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryByMzscBySfbzResponse")
	public com.ezsoft.prmInterfaceHIS2008.QueryByMzscBySfbzResponse.QueryByMzscBySfbzResult queryByMzscBySfbz(
			@WebParam(name = "sfbz", targetNamespace = "http://tempuri.org/") String sfbz);

}
