
package com.ezsoft.prmInterfaceHIS2008;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Service1HttpGet", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Service1HttpGet {

	/**
	 * 
	 * @param endtime
	 * @param starttime
	 * @param rqtype
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryInpatientInfo")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryInpatientInfo(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rqtype") String rqtype);

	/**
	 * 
	 * @param endtime
	 * @param starttime
	 * @param type
	 * @param content
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryOperationInfo")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryOperationInfo(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "type") String type,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "content") String content);

	/**
	 * 
	 * @param zyh
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryOperationInfoByZyh")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryOperationInfoByZyh(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh);

	/**
	 * 
	 * @param zyhm
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryInpatientDA")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryInpatientDA(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyhm") String zyhm);

	/**
	 * 
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryBrxz")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryBrxz();

	/**
	 * 
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "Querysf")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet querysf();

	/**
	 * 
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryJg")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryJg();

	/**
	 * 
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryMz")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryMz();

	/**
	 * 
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryGx")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryGx();

	/**
	 * 
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryZy")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryZy();

	/**
	 * 
	 * @param zyh
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryBrbl")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryBrbl(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh);

	/**
	 * 
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryMzKs")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryMzKs();

	/**
	 * 
	 * @param ksdm
	 * @param qsrq
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryKsMzPb")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryKsMzPb(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ksdm") String ksdm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "qsrq") String qsrq);

	/**
	 * 
	 * @param ksdm
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryKsBedInfo")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryKsBedInfo(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ksdm") String ksdm);

	/**
	 * 
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryBqKs")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryBqKs();

	/**
	 * 
	 * @param type
	 * @param content
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryZyjl")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryZyjl(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "type") String type,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "content") String content);

	/**
	 * 
	 * @param cypb
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryCypb")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String queryCypb(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cypb") String cypb);

	/**
	 * 
	 * @param cypb
	 * @param zyh
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryGrzk")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryGrzk(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cypb") String cypb);

	/**
	 * 
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryFymc")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryFymc();

	/**
	 * 
	 * @param zygb
	 * @param cypb
	 * @param zyh
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryXMMX")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryXMMX(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zygb") String zygb,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cypb") String cypb);

	/**
	 * 
	 * @param fyrq
	 * @param zygb
	 * @param cypb
	 * @param zyh
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryFYMX")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryFYMX(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zygb") String zygb,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fyrq") String fyrq,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cypb") String cypb);

	/**
	 * 
	 * @param rq
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryCyBirth")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryCyBirth(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rq") String rq);

	/**
	 * 
	 * @param rq
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryZyBirth")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryZyBirth(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rq") String rq);

	/**
	 * 
	 * @param rq
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryHfrw")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryHfrw(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rq") String rq);

	/**
	 * 
	 * @param zyhm
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryHfrwByZyhm")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryHfrwByZyhm(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyhm") String zyhm);

	/**
	 * 
	 * @param jlxh
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DeleteHfrwByJlxh")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String deleteHfrwByJlxh(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "jlxh") String jlxh);

	/**
	 * 
	 * @param zyh
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryInpatientInfoByZyh")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryInpatientInfoByZyh(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh);

	/**
	 * 
	 * @param zyhmc
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryInpatientInfoByZyhmc")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryInpatientInfoByZyhmc(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyhmc") String zyhmc);

	/**
	 * 
	 * @param ygdm
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryDocInfo")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryDocInfo(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ygdm") String ygdm);

	/**
	 * 
	 * @param zyh
	 * @param bz
	 * @param phonenum
	 * @param zyhm
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UpdatePhone")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String updatePhone(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyhm") String zyhm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "phonenum") String phonenum,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "bz") String bz);

	/**
	 * 
	 * @param phone
	 * @param content
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SentMessageToPat")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String sentMessageToPat(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "phone") String phone,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "content") String content);

	/**
	 * 
	 * @param phone
	 * @param content
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SentMsg")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String sentMsg(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "phone") String phone,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "content") String content);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetMsg")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getMsg();

	/**
	 * 
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryAllKS")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryAllKS();

	/**
	 * 
	 * @param zyh
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryHFInpatientInfoByZyh")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryHFInpatientInfoByZyh(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh);

	/**
	 * 
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryMZFZS")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryMZFZS(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime);

	/**
	 * 
	 * @param zyh
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryCYFileName")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryCYFileName(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh);

	/**
	 * 
	 * @param zyh
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryRYFileName")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryRYFileName(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh);

	/**
	 * 
	 * @param xz
	 * @param endDate
	 * @param startDate
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryCyFileString")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryCyFileString(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "xz") String xz,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "startDate") String startDate,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endDate") String endDate);

	/**
	 * 
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryPhoneManageByRyrq")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryPhoneManageByRyrq(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param ysgh
	 * @param rq
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryMzSpecialPationInfoByRqMzhmYsgh")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryMzSpecialPationInfoByRqMzhmYsgh(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzhm") String mzhm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ysgh") String ysgh,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rq") String rq);

	/**
	 * 
	 * @param zyh
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryZySpecialPationInfoByZyh")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryZySpecialPationInfoByZyh(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zyh") String zyh);

	/**
	 * 
	 * @param mzzyh
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryElectrocarDiogramByMZZYHAndTime")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryElectrocarDiogramByMZZYHAndTime(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzzyh") String mzzyh,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryMZbrda")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryMZbrda(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzhm") String mzhm);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryMZBrYJJC")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryMZBrYJJC(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzhm") String mzhm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime);

	/**
	 * 
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryYYGHByTime")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryYYGHByTime(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryYYGHByMZHM")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryYYGHByMZHM(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzhm") String mzhm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param pb
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UpdateJLBBZ")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String updateJLBBZ(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzhm") String mzhm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pb") String pb);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryLabItemNoByMzhmAndTime")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryLabItemNoByMzhmAndTime(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzhm") String mzhm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param labItemName
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryLisResultByMzhmAndTimeAndLabItemName")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryLisResultByMzhmAndTimeAndLabItemName(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzhm") String mzhm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LabItemName") String labItemName);

	/**
	 * 
	 * @param labItemNo
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryLisResultByLabItemNo")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryLisResultByLabItemNo(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LabItemNo") String labItemNo);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryJZJLByMzhmAndTime")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryJZJLByMzhmAndTime(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzhm") String mzhm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryBUltrasoundByMzhmAndTime")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryBUltrasoundByMzhmAndTime(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzhm") String mzhm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime);

	/**
	 * 
	 * @param mzhm
	 * @param endtime
	 * @param starttime
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryElectrocarDiogramByMzhmAndTime")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryElectrocarDiogramByMzhmAndTime(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mzhm") String mzhm,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "starttime") String starttime,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endtime") String endtime);

	/**
	 * 
	 * @param rq
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryJLBBirth")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryJLBBirth(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rq") String rq);

	/**
	 * 
	 * @param smID
	 * @param rq
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryMOMSG")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String queryMOMSG(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SM_ID") String smID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rq") String rq);

	/**
	 * 
	 * @param phone
	 * @param srcId
	 * @param id
	 * @param content
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SentMessageToPatByID")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String sentMessageToPatByID(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "id") String id,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "src_id") String srcId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "phone") String phone,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "content") String content);

	/**
	 * 
	 * @param sfbz
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryMzAtscBySfbz")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryMzAtscBySfbz(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sfbz") String sfbz);

	/**
	 * 
	 * @param jlxh
	 * @param sfbz
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UpdateMzAtscSfbz")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String updateMzAtscSfbz(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "jlxh") String jlxh,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sfbz") String sfbz);

	/**
	 * 
	 * @param sfbz
	 * @return returns org.tempuri.DataSet
	 */
	@WebMethod(operationName = "QueryByMzscBySfbz")
	@WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
	public DataSet queryByMzscBySfbz(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sfbz") String sfbz);

}
