
package com.enzemed.ios.validate;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* validate service = new validate();
* ValidateSoap portType = service.getValidateSoap();
* portType.getKey(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "validate", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://ios.enzemed.com/wxapp/appyun/validate.asmx?WSDL")
public class Validate extends Service {

	private final static URL VALIDATE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.enzemed.ios.validate.Validate.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.enzemed.ios.validate.Validate.class.getResource(".");
			url = new URL(baseUrl, "https://ios.enzemed.com/wxapp/appyun/validate.asmx?WSDL");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'https://ios.enzemed.com/wxapp/appyun/validate.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		VALIDATE_WSDL_LOCATION = url;
	}

	public Validate(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Validate() {
		super(VALIDATE_WSDL_LOCATION, new QName("http://tempuri.org/", "validate"));
	}

	/**
	 * 
	 * @return returns ValidateSoap
	 */
	@WebEndpoint(name = "validateSoap")
	public ValidateSoap getValidateSoap() {
		return super.getPort(new QName("http://tempuri.org/", "validateSoap"), ValidateSoap.class);
	}

	/**
	 * 
	 * @return returns ValidateSoap
	 */
	@WebEndpoint(name = "validateSoap12")
	public ValidateSoap getValidateSoap12() {
		return super.getPort(new QName("http://tempuri.org/", "validateSoap12"), ValidateSoap.class);
	}

}
