
package com.enzemed.ios.validate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "validateSoap", targetNamespace = "http://tempuri.org/")
public interface ValidateSoap {

	/**
	 * 
	 * @param id
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetKey", action = "http://tempuri.org/GetKey")
	@WebResult(name = "GetKeyResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetKey", targetNamespace = "http://tempuri.org/", className = "com.enzemed.ios.validate.GetKey")
	@ResponseWrapper(localName = "GetKeyResponse", targetNamespace = "http://tempuri.org/", className = "com.enzemed.ios.validate.GetKeyResponse")
	public String getKey(@WebParam(name = "id", targetNamespace = "http://tempuri.org/") String id);

	/**
	 * 
	 * @param id
	 * @param key
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetVaild", action = "http://tempuri.org/GetVaild")
	@WebResult(name = "GetVaildResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetVaild", targetNamespace = "http://tempuri.org/", className = "com.enzemed.ios.validate.GetVaild")
	@ResponseWrapper(localName = "GetVaildResponse", targetNamespace = "http://tempuri.org/", className = "com.enzemed.ios.validate.GetVaildResponse")
	public String getVaild(@WebParam(name = "id", targetNamespace = "http://tempuri.org/") String id,
			@WebParam(name = "key", targetNamespace = "http://tempuri.org/") String key);

}
